app/models/hearing_case_note.rb, app/models/prosecution_case.rb, app/models/prosecution_case_hearing_case_note.rb, db/migrate/20191023103236_create_hearing_case_notes.rb, db/migrate/20191023143956_create_prosecution_case_hearing_case_notes.rb, db/schema.rb, spec/factories/hearing_case_notes.rb, spec/factories/prosecution_case_hearing_case_notes.rb, spec/models/hearing_case_note_spec.rb, spec/models/prosecution_case_hearing_case_note_spec.rb, spec/models/prosecution_case_spec.rb, spec/support/schema_matchers.rb
Add HearingCaseNote and a has_many through relationship to ProsecutionCase
=> Add HearingCaseNote

app/models/applicant.rb, app/models/applicant_counsel.rb, app/models/attendance_day.rb, db/migrate/20191024100720_create_attendance_days.rb, db/migrate/20191024103912_create_applicant_counsels.rb, db/migrate/20191024104331_create_applicants.rb, db/schema.rb, spec/factories/applicant_counsels.rb, spec/factories/applicants.rb, spec/factories/attendance_days.rb, spec/models/applicant_counsel_spec.rb, spec/models/applicant_spec.rb, spec/models/attendance_day_spec.rb, spec/support/schema_matchers.rb
Depends/Includes https://github.com/ministryofjustice/hmcts-common-platform-mock-api/pull/52
=> Add applicant counsel

app/models/court_application_respondent.rb, app/models/court_application_response.rb, db/migrate/20191025101454_create_court_application_responses.rb, db/migrate/20191025103808_create_court_application_respondents.rb, db/schema.rb, spec/factories/court_application_respondents.rb, spec/factories/court_application_responses.rb, spec/models/court_application_respondent_spec.rb, spec/models/court_application_response_spec.rb, spec/support/schema_matchers.rb
Depends on https://github.com/ministryofjustice/hmcts-common-platform-mock-api/pull/62
=> Add CourtApplicationRespondent model and specs

app/models/defendant_hearing_youth_marker.rb, app/models/hearing.rb, db/migrate/20191028095223_create_hearings.rb, db/schema.rb, spec/factories/defendant_hearing_youth_markers.rb, spec/factories/hearings.rb, spec/models/defendant_hearing_youth_marker_spec.rb, spec/models/hearing_spec.rb, spec/support/schema_matchers.rb
Added model to map the schema for [hearing.json](https://github.com/ministryofjustice/hmcts-common-platform-mock-api/blob/8fcec6d7a4f348f14e1a4f92935904c67bac934b/spec/support/schemas/global/hearing.json)
=> Add Hearing model and specs

app/models/court_application_party.rb, db/migrate/20191107111424_change_court_application_party_defaults.rb, db/schema.rb, spec/factories/court_application_parties.rb, spec/models/court_application_party_spec.rb
Set Defendant, Organisation, Person, ProsecutingAuthority and RepOrganisation as optional.
=> Change CourtApplicationParty defaults

.env, Gemfile, Gemfile.lock, README.md, app/services/hearing_resulted_publisher.rb, lib/tasks/publish.rake, spec/cassettes/hearings/resulted/success.yml, spec/rails_helper.rb, spec/services/hearing_resulted_publisher_spec.rb, spec/support/vcr.rb, spec/tasks/publish_spec.rb
Publish HearingResulted to LAA via a rake task:
```
bundle exec rails 'publish:hearing[HEARING_ID]'
```
=> Post hearing resulted to LAA

README.md
Remove boilerplate text and add some basic set up instructions
=> Add set up instructions to readme

.env, .gitignore, app/services/hearing_resulted_publisher.rb, app/services/laa_connector.rb, helm_deploy/hmcts-common-platform-mock-api/templates/deployment.yaml, helm_deploy/hmcts-common-platform-mock-api/values.yaml, spec/cassettes/hearings/resulted/success.yml, spec/services/hearing_resulted_publisher_spec.rb, spec/services/laa_connector_spec.rb, spec/support/vcr.rb
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-234)
Add auth token for Mock to communicate with LAA Court data adaptor
=> Add auth token based authentication

.env, app/controllers/application_controller.rb, app/controllers/status_controller.rb, helm_deploy/hmcts-common-platform-mock-api/templates/deployment.yaml, spec/controllers/application_controller_spec.rb, spec/controllers/hearings_controller_spec.rb, spec/controllers/laa_references_controller_spec.rb, spec/controllers/prosecution_cases_controller_spec.rb, spec/rails_helper.rb, spec/requests/hearings_spec.rb, spec/requests/prosecution_cases_spec.rb, spec/support/authorised_request_helper.rb, spec/support/unauthorised_request.rb
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-234)
Move endpoints behind an auth wall, which can be triggered by passing in an authentication header.
=> Move endpoints behind authentication via shared token

Gemfile, Gemfile.lock, app/controllers/laa_references_controller.rb, app/models/defendant.rb, app/models/organisation.rb, app/models/person.rb, app/models/person_defendant.rb, app/services/prosecution_case_search.rb, config/routes.rb, lib/schemas/api/search-prosecutionCaseRequest.json, spec/controllers/laa_references_controller_spec.rb, spec/models/defendant_spec.rb, spec/models/organisation_spec.rb, spec/models/person_defendant_spec.rb, spec/models/person_spec.rb, spec/requests/hearings_spec.rb, spec/requests/prosecution_cases_spec.rb, spec/services/prosecution_case_search_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/-LASB327)
Edit the URL and schema to match CP search based on the integration tests with HCMTS.
Complements https://github.com/ministryofjustice/laa-court-data-adaptor/pull/132/ in CDA
=> Change urls to match CP SIT search

.rubocop.yml, spec/tasks/demo_data_helper_spec.rb
Enable latest cops:
`Layout/SpaceAroundMethodCallOperator`, `Lint/RaiseException`, `Lint/StructNewOverride` and `Style/ExponentialNotation`
=> Enable latest cops

app/controllers/hearings_controller.rb, app/models/hearing.rb, app/models/hearing_event.rb, app/services/hearing_log_finder.rb, config/routes.rb, db/migrate/20200423140547_create_hearing_events.rb, db/schema.rb, spec/controllers/hearings_controller_spec.rb, spec/factories/hearing_events.rb, spec/models/hearing_event_spec.rb, spec/models/hearing_spec.rb, spec/requests/hearings_spec.rb, spec/services/hearing_log_finder_spec.rb, spec/support/schema_matchers.rb
[Link to story](https://dsdmoj.atlassian.net/browse/CACP-329)
Add a new CP endpoint to show Hearing Logs/Events.
=> Add hearing event

app/controllers/hearings_controller.rb, db/migrate/20200519112230_add_alterable_to_hearing_event.rb, db/schema.rb, lib/schemas/api/hearing.api.hearingEventLogRequest.json, lib/schemas/api/hearing.api.hearingEventLogResponse.json, spec/factories/hearing_events.rb
[Link to story](https://dsdmoj.atlassian.net/browse/-CACP-90)
Updates to the mock schema based on HMCTS feedback.
=> Hearing log edits

README.md, docs/git-crypt.md
Add documentation around using `git-crypt`, borrowed from https://github.com/ministryofjustice/laa-apply-for-legal-aid
=> Add git-crypt docs

.gitignore, Gemfile, Gemfile.lock, app/assets/config/manifest.js, app/assets/stylesheets/application.css, app/channels/application_cable/channel.rb, app/channels/application_cable/connection.rb, app/helpers/application_helper.rb, app/views/layouts/application.html.erb, config/application.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/assets.rb, config/initializers/content_security_policy.rb, config/initializers/cookies_serializer.rb, public/404.html, public/422.html, public/500.html
To allow creation of Test Data via a simple admin interface, Re-initialising the mock as a full blown rails app.
=> Re-initialise as non-api-only app

config/routes.rb, spec/requests/hearings_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/CACP-436)
Change Mock URLs to match CP format.
=> Change URLS to match expected CP SIT format

.rubocop.yml, app/controllers/admin/prosecution_cases_controller.rb, app/models/hearing.rb, app/models/hearing_day.rb, app/models/hearing_event.rb, app/services/hearing_log_finder.rb, db/migrate/20200729144044_move_hearing_events_to_hearing_day.rb, db/schema.rb, spec/controllers/hearings_controller_spec.rb, spec/factories/hearing_events.rb, spec/models/hearing_day_spec.rb, spec/models/hearing_event_spec.rb, spec/models/hearing_spec.rb, spec/requests/hearings_spec.rb, spec/services/hearing_log_finder_spec.rb
Shift hearing events from hearings to hearing days, to ensure consistent results.
=> Fix hearing events

.rubocop.yml, app/controllers/admin/prosecution_cases_controller.rb
=> Enable new cops

app/controllers/admin/prosecution_cases_controller.rb, app/models/hearing.rb, app/models/prosecution_case.rb, app/views/admin/prosecution_cases/_form.html.erb, app/views/admin/prosecution_cases/_hearing.html.erb, db/migrate/20200805133146_add_hearings_to_prosecution_cases.rb, db/schema.rb, spec/factories/hearings.rb, spec/factories/prosecution_cases.rb, spec/models/prosecution_case_spec.rb, spec/requests/admin/prosecution_cases_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/CACP-456)
1 To ensure we have a HearingSummary present, added a validation.
2. Added a hearing when creating a case via the admin ui
3. Added a migration to fix existing records.
=> Ensure all cases have at least one hearing

.circleci/config.yml, Gemfile, Gemfile.lock, app/views/admin/prosecution_cases/_add_offence.html.erb, spec/features/add_case_spec.rb, spec/rails_helper.rb, spec/spec_helper.rb, spec/support/capybara.rb, spec/support/when_authenticated.rb
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=398&projectKey=CACP&modal=detail&selectedIssue=CACP-467
Fix to ensure new offence is attached to Prosecution Case. Adding new offences to Prosecution Case allows for testing of different scenarios
=> Fix to ensure new offence is attached to Prosecution Case

Gemfile.lock
Build fix - update bundler and Gemfile
=> Update bundler and Gemfile

spec/factories/hearings.rb
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=398&projectKey=CACP&modal=detail&selectedIssue=CACP-468
HMCTS CP Mock generates courts which are known to work in the MLRA
=> FactoryBot to generate courts based on a chosen friendly court id

app/models/prosecution_case_identifier.rb, app/services/prosecution_case_search.rb, lib/schemas/api/search-prosecutionCaseRequest.json, spec/services/prosecution_case_search_spec.rb
[Link to story]https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=454&projectKey=LASB&modal=detail&selectedIssue=LASB-364
Instead of accepting one of URN/ASN/NINO or Name and DOB, allow a combination of these.
Search function within mock updated to allow multi-parameter search 
=> allow multiple parameters in search criteria'

config/locales/faker.en.yml, lib/faker/offence.rb, spec/factories/offences.rb
Add realistic mode of trial to factory
Extend custom offence faker and use in factory
for more realistic data. This is an important
field for view court data.
[Link to story](https://dsdmoj.atlassian.net/browse/CBO-1575)
=> Add realistic mode of trial to factory

app/services/prosecution_case_search.rb, spec/services/prosecution_case_search_spec.rb
[Link to story]https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=454&projectKey=LASB&modal=detail&selectedIssue=LASB-364
There was an exception that was being generated for certain search criteria. this has now been fixed
=> Fixed exception that was being generated

config/locales/faker.en.yml, lib/faker/offence.rb, spec/factories/allocation_decisions.rb
Add realistic mode of trial reasons
Both for tests and demo data creation.
=> Add realistic mode of trial reasons

app/views/admin/prosecution_cases/show.html.erb, spec/views/admin/prosecution_cases/show.html.erb_spec.rb
[Link to story]https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=454&projectKey=LASB&modal=detail&selectedIssue=LASB-424
Code modified so user can view defendant information against the prosecution case it belongs to.
=> Display defendant information against Prosecution Cases in the mock

app/views/admin/prosecution_cases/add_offence.js.erb
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=454&projectKey=LASB&modal=detail&selectedIssue=LASB-367
Ensure the orderIndex on each offence is unique so data can be correctly displayed in other Crime Apps
=> Fix to ensure Offence orderIndex values are unique

app/models/judicial_result.rb, app/views/admin/prosecution_cases/_judicial_result.html.erb
Allow blank PostHearingCustodyStatus, since that is valid according to the CP schema.
=> Allow blank Post hearing custody status

app/models/concerns/builder_mappable.rb, app/models/defendant.rb, app/models/hearing.rb, app/models/offence.rb, app/models/prosecution_case.rb, spec/models/hearing_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/-LASB-422)
Render pleas/verdicts against offences in the context of a hearing
Part 4 of 4
=> Render pleas/verdicts against offences in the context of a hearing

app/controllers/admin/hearings_controller.rb, app/models/defendant.rb, app/models/hearing.rb, app/models/offence.rb, app/views/admin/hearings/_add_plea.html.erb, app/views/admin/hearings/_form.html.erb, app/views/admin/hearings/_plea_fields.html.erb, app/views/admin/hearings/add_plea.js.erb, config/routes.rb, spec/factories/organisations.rb, spec/models/defendant_spec.rb, spec/requests/admin/hearings_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-422)
Part 3 of 4
=> Enable creation of pleas against hearings/offences

Gemfile, Gemfile.lock, app/models/plea.rb, lib/tasks/demo_data_helper.rb, lib/tasks/demodata.rake, spec/factories/defence_counsels.rb, spec/factories/pleas.rb, spec/tasks/demo_data_helper_spec.rb, spec/tasks/demodata_spec.rb
Extend demo data to:
- add hearings, days and events
- offence allocation_decisions and pleas
- increase test coverage
This is to enable creation of a standard set of
queryable data on any environment (local
or hosted)
=> Extend demo data

.dockerignore, .editorconfig
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-385)
Add Editorconfig
=> Add editorconfig

spec/factories/prosecution_case_identifiers.rb
[Link to story]https://dsdmoj.atlassian.net/browse/LASB-479
=> when creating a prosecution case always default URN

app/views/admin/defendants/show.html.erb
[Link to story]https://dsdmoj.atlassian.net/browse/LASB-435
Defendant show page updated to add navigation links
=> add back and edit buttons to defendant show page

lib/tasks/demo_data_helper.rb, lib/tasks/demodata.rake, spec/tasks/demo_data_helper_spec.rb, spec/tasks/demodata_spec.rb
[CBO-1617](https://dsdmoj.atlassian.net/browse/CBO-1617)
Extend demo data generator to add a cracked/ineffective
trial to the "other" case that "Jammy Dodger" is
defendant on - TEST54321.
So we can have a case with cracked ineffective trial details
for demonstration purposes.
=> Extend demo data generator to include cracked ineffective trials

spec/views/admin/defendants/edit.html.erb_spec.rb
Added basic test to defendant edit spec that had been auto generated and was being skipped
=> add test to skipped template spec

app/controllers/admin/hearings_controller.rb, app/models/allocation_decision.rb, app/models/offence.rb, app/views/admin/hearings/_add_allocation_decision.html.erb, app/views/admin/hearings/_allocation_decision_fields.html.erb, app/views/admin/hearings/_form.html.erb, app/views/admin/hearings/add_allocation_decision.js.erb, config/routes.rb, spec/models/hearing_spec.rb, spec/requests/admin/hearings_spec.rb
Include functionality to add an allocation decision against a hearing - this allows for the creation of data for future testing.
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=454&projectKey=LASB&modal=detail&selectedIssue=LASB-484
=> Lasb 484 manually populate allocation decision

.circleci/config.yml
Add 's' to timeout length for helm upgrade
=> Add 's' to timeout length on upgrade

.circleci/config.yml
Update Helm client to latest version.
=> Bump Helm from 3.2.4 to 3.5.0

.circleci/config.yml
=> Set wait flag to false

app/controllers/admin/hearings_controller.rb, app/controllers/admin/pleas_controller.rb, app/views/admin/hearings/_form.html.erb, config/routes.rb, spec/requests/admin/hearings_spec.rb, spec/requests/admin/pleas_spec.rb
Refactor to use a RESTful approach for the `Plea` resource.
Similar to https://github.com/ministryofjustice/hmcts-common-platform-mock-api/pull/379.
=> Use RESTful route for Plea resource

app/controllers/admin/allocation_decisions_controller.rb, app/controllers/admin/hearings_controller.rb, config/routes.rb, spec/requests/admin/allocation_decisions_spec.rb, spec/requests/admin/hearings_spec.rb
Refactor to use a RESTful approach for the `AllocationDecision` resource.
=> Use RESTful route for AllocationDecision resource

app/views/admin/hearings/_form.html.erb
=> Remove add judicial result link

app/controllers/admin/judicial_results_controller.rb, app/views/admin/hearings/show.html.erb, db/schema.rb, spec/factories/judicial_results.rb, spec/requests/admin/judicial_results_spec.rb
=> Add a new judicial result from hearing show page

app/views/admin/hearings/_form.html.erb
[Link to story]https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=454&projectKey=LASB&modal=detail&selectedIssue=LASB-516
Removed next hearing fields from edit hearing page
=> removed next hearing from edit hearing page

.circleci/config.yml
Update to the the circleci/helm orb
=> Fix build 

db/migrate/20210406103836_update_prosecution_case_identifier.rb, db/schema.rb
Fixes the build.
Build failing because of: `PG::NotNullViolation: ERROR:  column "contact_number_id" contains null values`
=> Fix migration

app/models/hearing_event.rb, db/migrate/20210506124837_add_note_to_hearing_events.rb, db/schema.rb, lib/schemas/api/hearing.api.hearingEventLogResponse.json, lib/tasks/demodata.rake, spec/factories/hearing_events.rb
https://dsdmoj.atlassian.net/browse/AAC-62
Add note field to hearing event to enable testing of hearing event freetext in VCD.
=> Add note to hearing event

.circleci/config.yml
=> Update aws/ecr orb to 7.0.0

app/controllers/admin/court_application_types_controller.rb, app/controllers/admin/court_applications_controller.rb, app/controllers/admin/judicial_results_controller.rb, app/controllers/admin/respondents_controller.rb, app/models/court_application.rb, app/models/court_application_party.rb, app/models/court_application_type.rb, app/models/hearing.rb, app/models/judicial_result.rb, app/views/admin/court_application_types/_form.html.erb, app/views/admin/court_application_types/edit.html.erb, app/views/admin/court_applications/_form.html.erb, app/views/admin/court_applications/edit.html.erb, app/views/admin/court_applications/show.html.erb, app/views/admin/hearings/show.html.erb, app/views/admin/judicial_results/_form.html.erb, app/views/admin/judicial_results/edit.html.erb, app/views/admin/judicial_results/show.html.erb, app/views/admin/respondents/_form.html.erb, app/views/admin/respondents/edit.html.erb, config/routes.rb, db/migrate/20210525135110_add_court_application_reference_to_court_application_parties.rb, db/schema.rb, spec/factories/court_application_parties.rb, spec/factories/court_applications.rb, spec/factories/hearings.rb, spec/factories/judicial_results.rb, spec/models/court_application_spec.rb, spec/requests/admin/judicial_results_spec.rb
Adds CRUD for court applications and associations:
* court application type
* court application respondents (court application party)
Ticket: https://dsdmoj.atlassian.net/browse/LASB-590
=> CRUD for court applications and associations

app/controllers/admin/hearing_days_controller.rb, app/views/admin/hearing_days/_form.html.erb, app/views/admin/hearing_days/edit.html.erb, app/views/admin/hearing_days/show.html.erb, app/views/admin/hearings/show.html.erb, config/routes.rb, spec/requests/admin/hearing_days_spec.rb
Refactor routes for hearing days to use Rails's `resources` helper.
=> Refactor hearing days routes

lib/schemas/global/apiProsecutingAuthority.json, lib/schemas/global/apiProsecutionCaseIdentifier.json
Add updated schema files to project to ensure that we have full visibility of data exchange with HMCTS.
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=454&projectKey=LASB&modal=detail&selectedIssue=LASB-608
=> Add updated schema files

.github/workflows/brakeman.yml, Gemfile, Gemfile.lock
[Link to story]https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=454&projectKey=LASB&modal=detail&selectedIssue=LASB-622
Brakeman for static analysis added to mock
=> Brakeman analysis tool added to mock

app/views/admin/court_applications/edit.html.erb, app/views/admin/judicial_results/edit.html.erb
[Link to story]https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=454&projectKey=LASB&modal=detail&selectedIssue=LASB-698
On edit Judicial Result and edit Court Application views, added Back button to return to the show Hearing view.
=> added back buttons to mock edit views

app/models/offence.rb, app/models/offence_summary.rb
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-750)
Updated OffenceSummary model to include plea information.
=> Include plea details in OffenceSummary

app/models/offence.rb, app/models/offence_summary.rb, lib/schemas/global/search/apiOffenceSummary.json, spec/models/offence_summary_spec.rb
Render pleas in search prosecution case response in line with schema. This ensures a prosecution case payload with plea data for testing in CDA etc can be created.
=> Render pleas in search prosecution case response in line with schema

.circleci/config.yml
=> add circleci ruby orb

Dockerfile, docker/run
Set bundler directory for Docker to write to
=> set bundler directory

Dockerfile
adjust dockerfile ENV setting order
=> adjust dockerfile ENVs

.circleci/config.yml, Dockerfile, docker/run
Use official ruby alpine image in dockerfile
=> use official ruby alpine image in dockerfile

app/models/concerns/court_centre_relatable.rb, app/models/court_centre.rb, app/views/admin/hearing_days/_form.html.erb, app/views/admin/hearings/_form.html.erb, app/views/admin/judicial_results/_form.html.erb, app/views/admin/prosecution_cases/_hearing.html.erb, lib/data/court_centres_sample.yml, spec/factories/hearing_days.rb, spec/factories/hearings.rb, spec/models/court_centre_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/-LASB731)
Create sample court centre list locally to use as selector for drop downs. 
Move towards deprecating hmcts_common_platform gem
=> use local sample list of court centres for dropdowns

app/views/admin/hearings/show.html.erb, spec/views/admin/hearings/show.html.erb_spec.rb
Display the verdict when viewing a hearing.
=> Display verdict when viewing a hearing

.git-crypt/keys/default/0/D98A8671566BD840D4BDACD4F835A1DB11AFD38F.gpg
New collaborators:
11AFD38F Ahilan Santhanlingam <ahilan.santhanlingam@digital.justice.gov.uk>
=> Add 1 git-crypt collaborator

.circleci/config.yml
Specify custom location of Helm values file.
=> Specify location of Helm values file

README.md
Add MOJ repo standards badge to README
=> Add MOJ repo standards badge to README

package.json, yarn.lock
=> Upgrade npm dependencies

app/models/hearing_day.rb, app/models/hearing_summary.rb, db/migrate/20220510151638_add_has_shared_results_to_hearing_days.rb, db/schema.rb, lib/schemas/global/apiHearingDay.json, lib/schemas/global/search/apiHearingSummary.json, spec/factories/hearing_days.rb
Add hasSharedResults boolean flag to hearing day
=> Add hasSharedResults boolean flag to hearing day

app/models/offence_summary.rb, lib/schemas/global/search/apiOffenceSummary.json
Revert code that turned pleas into an object to allow for the array to come through. 
=> Revert pleas to be an array

.circleci/config.yml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-2638)
=> LASB-2638 - Short lived credentials update

.gitignore, app/views/admin/prosecution_cases/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-2963)
=> LASB-2963: Default to using dev SQS queues

app/controllers/application_references_controller.rb, app/models/court_application_defendant_summary.rb, app/services/application_reference_recorder.rb, app/services/laa_reference_recorder.rb, config/routes.rb, lib/schemas/api/progression.recordApplicationReference.json, spec/requests/laa_references_spec.rb, spec/services/application_reference_recorder_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/ACD-595)
- Added a new endpoint that creates or updates an LaaReference object with details passed in relating to a given application
- This will be returned as part of the `application` payload under `subjectSummary->offenceSummary->laaApplnReference` when #854 is merged
=> ACD-585: Application link API

app/models/court_application.rb, app/models/court_application_summary.rb, app/models/prosecution_case_court_application_summary.rb, db/migrate/20250403105947_add_short_code_to_court_applications.rb, db/schema.rb, spec/models/court_application_spec.rb, spec/models/court_application_summary_spec.rb, spec/models/prosecution_case_court_application_summary_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/ACD-646)
[Link to story](https://dsdmoj.atlassian.net/browse/ACD-627)
Auto-generate a short code on court application creation. Include it in payloads of prosecution case searches and court application retrievals
=> ACD-646 & ACD-627: Short codes

app/controllers/admin/court_application_hearing_controller.rb, app/controllers/admin/court_applications_controller.rb, app/models/court_application.rb, app/models/court_application_summary.rb, app/views/admin/court_applications/_hearings.html.erb, app/views/admin/court_applications/show.html.erb, config/routes.rb, spec/requests/admin/court_application_hearing_spec.rb, spec/requests/admin/court_applications_controller_spec.rb
[ACD-630](https://dsdmoj.atlassian.net/browse/ACD-630)
User can now associate multiple hearings to a court application from the same prosecution case.
[ACD-630]: https://dsdmoj.atlassian.net/browse/ACD-630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Implementation of multiple hearings associated with a court application

app/models/court_application.rb, app/models/court_application_summary.rb, app/models/hearing_summary.rb, app/views/admin/hearings/show.html.erb, spec/factories/court_applications.rb, spec/models/court_application_summary_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/ACD-567)
Send a result code in the application summary
=> ACD-567: Send a result code

app/models/court_application_type.rb
[Link to story](https://dsdmoj.atlassian.net/browse/-ACD-669)
Remove fields that HMCTS does not send
=> ACD-669: Remove fields from schema that HMCTS does not send

app/controllers/admin/application_controller.rb, app/controllers/admin/court_applications_controller.rb, app/controllers/admin/defendants_controller.rb, app/controllers/admin/hearings_controller.rb, app/controllers/admin/prosecution_cases_controller.rb, app/models/breadcrumb_list.rb, app/views/layouts/admin/_breadcrumbs.html.erb, app/views/layouts/admin/application.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/-ACD-664)
Add some simple breadcrumbs to make navigation easier
=> ACD-664: Add some breadcrumbs

.circleci/config.yml, README.md, docker-compose.yml
=> ACD-805: Bump local and CI postgres versions

.circleci/config.yml
[Link to story](https://dsdmoj.atlassian.net/browse/ACD-905)
=> ACD-905: Integrate E2E tests

app/models/court_application.rb, app/models/laa_reference.rb, app/services/laa_reference_recorder.rb, app/services/laa_representation_order_recorder.rb, db/migrate/20250902080512_add_court_application_id_to_laa_reference.rb, db/schema.rb, spec/services/laa_reference_recorder_spec.rb, spec/services/laa_representation_order_recorder_spec.rb
If an application ID is passed in, link to the application
[Link to story](https://dsdmoj.atlassian.net/browse/ACD-948)
=> ACD-948 & ACD-950: Allow application-level linking

app/services/laa_reference_recorder.rb, app/services/laa_representation_order_recorder.rb, config/routes.rb, lib/schemas/api/progression.recordApplicationReference.json, lib/schemas/api/progression.recordLAAReference.json, lib/schemas/api/progression.recordRepresentationOrder.json, spec/services/laa_reference_recorder_spec.rb, spec/services/laa_representation_order_recorder_spec.rb
Late in the day the API designs for linking no-offence court applications changed. Update the mock accordingly
=> ACD-948-b: (Breaches/POCA) Reflect new endpoint design

lib/tasks/demodata.rake, spec/factories/court_application_types.rb, spec/tasks/demodata_spec.rb
The goal of this PR is to create data to test the appeal case using the e2e testing.
**NOTE:** 
The search by URN "TESTAP123" does not show any results. I am still investigating the reason.
https://dsdmoj.atlassian.net/browse/ACD-908
=> Create seed data for appeal to e2e test.
