app/services/prosecution_case_search.rb, config/routes.rb, spec/requests/prosecution_cases_spec.rb, spec/services/prosecution_case_search_spec.rb, spec/spec_helper.rb
1. Run the webmocked specs only for model and request specs, and in other cases, (i.e, services) we rely on the local file paths to read and validate the json schemas. This is important as we are now using a schema to validate the request params as well, and we need to ensure that the specs are reflecting the actual use, rather than 'faking' a request.
2. This requires us to manually register additonal ref schemas, to ensure that the json-schema validator can find the references relative to the given schema.
3. ProsecutionCases can be queried by either
a) prosecutionCaseReference,
b) nationalInsuranceNumber,
c) arrestSummonsNumber,
d) name and dateOfBirth, or
e) name and dateOfNextHearing
This PR handles a) prosecutionCaseReference and b) nationalInsuranceNumber
We are assuming that …
=> Search Prosecution Cases by prosecutionCaseReference

app/models/defendant.rb, app/models/person.rb, app/models/person_defendant.rb, app/models/prosecution_case.rb, app/services/prosecution_case_search.rb, spec/models/defendant_spec.rb, spec/models/person_defendant_spec.rb, spec/models/person_spec.rb, spec/models/prosecution_case_spec.rb, spec/services/prosecution_case_search_spec.rb
Add functionality to allow searching by arrestSummonsNumber or DateOfBirth and Name.
The name is modelled on [defendantName.json](https://github.com/ministryofjustice/hmcts-common-platform-mock-api/blob/4e216ae24c4596c9b0d4c4f7721f3fc57df33525/lib/schemas/global/search/defendantName.json), i.e, it expects `firstName`, `lastName` and optionally `middleName`
=> Add prosecution case search params

app/controllers/application_controller.rb, app/controllers/hearings_controller.rb, app/services/hearing_finder.rb, config/routes.rb, lib/schemas/api/hearing-resulted.json, lib/schemas/api/progression.recordLAAReference.json, lib/schemas/api/progression.recordRepresentationOrder.json, lib/schemas/api/results.hearingResultedRequest.json, lib/schemas/api/results.hearingResultedResponse.json, spec/controllers/application_controller_spec.rb, spec/controllers/hearings_controller_spec.rb, spec/requests/hearings_spec.rb, spec/services/hearing_finder_spec.rb, spec/support/fake_common_platform.rb, spec/support/schema_matchers.rb
A request can be made using the suggested URL of
`hearing/results/:hearingId`
Additionally, added a default error-handling mechanism to render a 404 in case of a non-existent ID.
=> Get hearing results api

helm_deploy/hmcts-common-platform-mock-api/values.yaml
By allowing the access to the API from outside K8s we will be able to
test the API responses from developers machines.
In order to allow this, we need to enable the ingress in our service.
=> Enable Ingress to allow access from outside k8s

helm_deploy/hmcts-common-platform-mock-api/values.yaml
Specifying the "path" key under "paths" instead of directly the path
values was being translated into "path:path:/" in the template.
=> Fix Ingress path

Dockerfile, Gemfile, Gemfile.lock
json-schema is a dependency in `json-schema-rspec` and hence only available in development and test environments.
This PR makes it available in production, and also prevents development/test gems from being loaded in production.
=> Avoid spring from booting in production and require json-schema in production

app/models/laa_reference.rb, spec/models/laa_reference_spec.rb
According to the HMCTS schema specification for LAA Reference entity,
effectiveStartDate and effectiveEndDate are optional values.
During testing against this mock api was discovered that the Json
builder was blowing up as the Laa Reference stored in DB does not
contain those date values, but the Json builder assumes its existence
and tries to cast them into a date.
This commit fixes it by returning null for those values when they are
not defined in the database.
=> Allow missing dates in LAA Reference JSON response

app/controllers/prosecution_cases_controller.rb, app/models/applicant_counsel.rb, app/models/concerns/builder_mappable.rb, app/models/court_application.rb, app/models/court_application_party.rb, app/models/court_application_party_attendance.rb, app/models/court_application_party_counsel.rb, app/models/defence_counsel.rb, app/models/defendant.rb, app/models/defendant_summary.rb, app/models/hearing.rb, app/models/hearing_case_note.rb, app/models/hearing_summary.rb, app/models/judicial_result.rb, app/models/judicial_result_prompt.rb, app/models/merged_prosecution_case.rb, app/models/next_hearing.rb, app/models/next_hearing_defendant.rb, app/models/next_hearing_prosecution_case.rb, app/models/offence.rb, app/models/prosecution_case.rb, app/models/prosecution_case_summary.rb, app/models/prosecution_counsel.rb, app/models/respondent_counsel.rb
Refactored to move common array builder attributes to a concern.
Also, since we have have [defaulted to ignoring `nil` attributes](https://github.com/ministryofjustice/hmcts-common-platform-mock-api/blob/master/config/initializers/jbuilder.rb#L3) we no longer need many of the original conditional checks.
=> Refactor array builder to concern

.gitignore, Gemfile, Gemfile.lock, spec/models/prosecution_case_summary_spec.rb, spec/spec_helper.rb
This PR:
* Adds `simplecov` to the gemfile
* Configures `simplecov` to mandate 100% code coverage and not include specs in the coverage calculation
* Updates `.gitignore` to prevent code coverage details being committed
* Adds an extra test to `prosecution_case_summary_spec` to ensure 100% coverage
=> Add simplecov gem to monitor test coverage

app/controllers/hearings_controller.rb, app/controllers/laa_references_controller.rb, app/controllers/prosecution_cases_controller.rb, config/routes.rb, spec/controllers/hearings_controller_spec.rb, spec/controllers/laa_references_controller_spec.rb, spec/controllers/prosecution_cases_controller_spec.rb, spec/requests/hearings_spec.rb, spec/requests/prosecution_cases_spec.rb
Several API paths include the string `-sit`. HMCTS have informed us that their APIs do not include this, so we should remove it from the mock.
=> Remove '-sit' from urls

spec/factories/hearings.rb
To return more realistic data from the mock to CDA, amend the `hearings` factory to add a trait so that a `prosecution_case` is created. This causes a `hearing_summary` to be created and included in the prosecution case search response.
=> Add prosecution_case trait to hearings factory

spec/factories/applicant_counsels.rb, spec/factories/defence_counsels.rb, spec/factories/person_defendants.rb
Update seeds to have [real looking values](https://github.com/ministryofjustice/hmcts-common-platform-mock-api/pull/79#discussion_r383226408)
Changed: 
ApplicantCounsel and DefendantCounsel to have a status similar to "Leading counsel"
PersonDefendant to have perceivedBirthYear between 1950 and 2020
=> Update defendant seeds with clearer values

app/models/person.rb
To be inline with [schema regex definition](https://github.com/ministryofjustice/hmcts-common-platform-mock-api/blob/6955ae92a00efe5adc924eba2f5aaf3e658b97f9/lib/schemas/global/courtsDefinitions.json#L213-L216)
Meant was generating random data with NI numbers that could not
be searched for adaptor and returning, for example:
```
{"error"=>"[\"The property '#/nationalInsuranceNumber' value \\\"HR669639M\\\" did not match the regex '(?!BG)(?!GB)(?!NK)(?!KN)(?!TN)(?!NT)(?!ZZ)(?:[A-CEGHJ-PR-TW-Z][A-CEGHJ-NPR-TW-Z])(?:\\\\s*\\\\d\\\\s*){6}([A-D]|\\\\s)$' in schema http://justice.gov.uk/unified_search_query/global/courtsDefinitions.json#\"]"}
```
Amended regex for national insurance number so it generates
NINOs that are valid against the schema from hmcts Common platform
Before you ask people …
=> Amend factory national insurance number faker regex

app/services/prosecution_case_search.rb, lib/schemas/api/search-prosecutionCaseRequest.json, spec/services/prosecution_case_search_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/CACP-297)
Change dateOfBirth to be defendantDOB to match CP format.
The schema changes have been sent across to HMCTS to review.
=> Fix defendantDOB to match CP format

.rubocop.yml
Fix the following warning by setting both cops to `Enabled: true`:
```
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
- Layout/EmptyLinesAroundAttributeAccessor (0.83)
- Style/SlicingWithRange (0.83)
For more information: https://docs.rubocop.org/en/latest/versioning/
```
=> Add new cops to .rubocop.yml

.env, app/controllers/application_controller.rb, app/controllers/hearings_controller.rb, app/controllers/laa_references_controller.rb, app/controllers/prosecution_cases_controller.rb, app/models/defendant.rb, app/models/person_defendant.rb, app/services/hearing_log_finder.rb, config/routes.rb, helm_deploy/hmcts-common-platform-mock-api/templates/deployment.yaml, lib/schemas/api/hearing.api.hearingEventLogRequest.json, lib/schemas/api/hearing.api.hearingEventLogResponse.json, spec/controllers/application_controller_spec.rb, spec/controllers/hearings_controller_spec.rb, spec/controllers/laa_references_controller_spec.rb, spec/controllers/prosecution_cases_controller_spec.rb, spec/models/defendant_spec.rb, spec/models/person_defendant_spec.rb, spec/requests/hearings_spec.rb, spec/requests/prosecution_cases_spec.rb, spec/services/hearing_log_finder_spec.rb
This PR is necessary to support changes done in https://github.com/ministryofjustice/laa-court-data-adaptor/pull/157
[Link to story](https://dsdmoj.atlassian.net/browse/CACP-368)
Edits the mock to allow it to work with CDA, incorporating hearing events changes and more closely matching CP SIT.
1. Modifed the schema to match Hearing logs endpoint: The endpoint requires a date + hearing id, as seen in CP SIT. This will be confirmed with HMCTS.
2. Refactored to move authentication to application controller as all the endpoints use the same key now.
3. In the Prosecution case search, edited the Content-type header value to `application/vnd.unifiedsearch.query.laa.cases+json` as seen in SIT
4. Allowed PersonDefendant.custodyTimeLimit value to be optional. 
5. Fetch Hearings by next_hearing …
=> Edit mock to match CP in SIT

Dockerfile
Ensure assets are precompiled for the css based view.
Also, we no longer need to create the `/tmp/pids` directory as that is [checked into source control](https://github.com/ministryofjustice/hmcts-common-platform-mock-api/blob/20acc467c9ec9dddfbfb6dc2075ed72461167ea8/.gitignore#L18)
=> Update Dockerfile to ensure assets are precompiled

app/controllers/hearings_controller.rb, lib/schemas/api/results.api.hearingResultedResponse.json
CP wraps the responses in a json object containg `hearing` and `sharedTime`
This change makes the mock output match the SIT format.
=> Match GET Hearings output to CP SIT

.rubocop.yml, app/models/hearing.rb, app/models/prosecution_case.rb, app/models/prosecution_case_hearing.rb, app/models/prosecution_case_summary.rb, config/puma.rb, db/migrate/20200703152351_create_prosecution_case_hearings.rb, db/schema.rb, spec/factories/prosecution_case_hearings.rb, spec/factories/prosecution_case_identifiers.rb, spec/factories/prosecution_cases.rb, spec/models/hearing_spec.rb, spec/models/prosecution_case_hearing_spec.rb, spec/models/prosecution_case_spec.rb, spec/models/prosecution_case_summary_spec.rb
Since CP schema allows multiple hearings to be sent as part of a `ProsecutionCase` search payload, this PR maps the relationship a bit more accurately. 
=> Convert ProsecutionCase <> Hearing relationship to a has many through to reflect the CP structure more accurately

app/models/offence.rb
Add safe navigation to `.to_date` calls in offence jbuilder
Was erroring when calling hearing endpoint
=> Add safe navigation to `.to_date` calls in offence jbuilder

app/models/defence_counsel.rb, app/models/prosecution_counsel.rb, spec/models/defence_counsel_spec.rb, spec/models/prosecution_counsel_spec.rb
Not too sure of the impact of destroying attndance days,
nullifying a defendants defence counsel or case's
prosecution counsel but...
To make removing prosecution and defence counsel from hearings
easier/possible without violating FK contraints.
previously was having to do this
```
hearing.prosecution_counsels.first.prosecution_cases.first.update(prosecution_counsel_id: nil)
hearing.prosecution_counsels.first.destroy
```
with these you can just
```
hearing.prosecution_counsels.destroy_all
[hearing.defence_counsels.destroy_all]
```
[ticket CBO-1378](https://dsdmoj.atlassian.net/browse/CBO-1378)
=> Add model relation dependency changes

db/migrate/20200703152351_create_prosecution_case_hearings.rb
Amend migration to handle prosecution cases with no hearings
Currently running the migration in my environment
results in constraint violation as the select is returning
prosecution cases without a hearing, and hearing_id cannot
be null.
=> Amend migration to handle prosecution cases with no hearings

app/models/prosecution_case_identifier.rb, app/services/prosecution_case_search.rb, spec/services/prosecution_case_search_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/CBO-1401)
Allow searching across mixed/up/down cased values in the mock to better reflect CP Search.
=> Add mixed case search functionality

app/models/lesser_or_alternative_offence.rb, app/models/offence.rb, db/migrate/20200803133825_change_offence_code_value.rb, db/schema.rb, spec/factories/lesser_or_alternative_offences.rb, spec/factories/offences.rb, spec/models/lesser_or_alternative_offence_spec.rb, spec/models/offence_spec.rb
Limit OffenceCode to max 8 characters. 
To ensure compatibility with the format expected by MLRA:
```
Caused by: oracle.jdbc.OracleDatabaseException: ORA-12899: value too large for column "MLA"."XXMLA_XLAT_OFFENCE"."OFFENCE_CODE" (actual: 13, maximum: 8)
2020-08-03T12:30:41.764+01:00
```
=> Add length constraints to offenceCode

app/models/prosecution_case_identifier.rb, spec/models/prosecution_case_identifier_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/CACP-457)
Since CP does not allow prefix/suffix searches
=> Change caseURN search to exact match

app/models/defendant_summary.rb, app/models/person.rb, lib/schemas/global/search/apiDefendantSummary.json, spec/models/person_spec.rb
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=398&projectKey=CACP&modal=detail&selectedIssue=CACP-502
Break down Defendant name to be displayed as separate fields of first/middle/last name when the Defendant is a person.
=> Cacp 502 cp mock to render name breakdown

app/controllers/admin/prosecution_cases_controller.rb, app/javascript/packs/application.js, app/views/admin/prosecution_cases/_add_offence.html.erb, app/views/admin/prosecution_cases/_defendant.html.erb, app/views/admin/prosecution_cases/add_offence.js.erb, config/routes.rb, package.json, spec/requests/admin/prosecution_cases_spec.rb, yarn.lock
https://dsdmoj.atlassian.net/browse/CACP-511
Include ability to add additional offences to prosecution case with auto populated form to enable testing of different scenarios
=> Cacp 511 auto populate when adding new offence

app/models/defendant.rb, spec/requests/admin/prosecution_cases_spec.rb
[Link to story]https://dsdmoj.atlassian.net/browse/LASB-362
When an offence is removed and the Prosecution Case saved, when re-accessing the case the offence should not be displayed on screen or be part of the code logic.
=> Enable Remove button to work in mock

lib/tasks/demo_data_helper.rb, lib/tasks/demodata.rake, spec/tasks/demo_data_helper_spec.rb, spec/tasks/demodata_spec.rb
Add allocation decisions to demo data example defendant
[CBO-1575 display allocation decisions](https://dsdmoj.atlassian.net/browse/CBO-1575)
The allocation decisions, and specifically
the motReasonDescription is important for
View court data - it impacts value of
fee claimable by providers.
=> Add allocation decisions to demo data

app/models/hearing.rb, app/models/hearing_day.rb, spec/models/hearing_day_spec.rb, spec/models/hearing_spec.rb
Add dependent destroy relations for hearings
hearing days cannot exist without a hearing
and hearing events cannot exist with
a hearing day.
When unloading demo data not having these
depedencies causes failures - cannot destroy
parents because children exist.
=> Add hearing related dependent destroy relations

.circleci/config.yml
Similar to https://github.com/ministryofjustice/laa-court-data-adaptor/pull/358, for the mock.
Upgrade helm orb to 1.1.2, as the helm charts at https://kubernetes-charts.storage.googleapis.com are no longer publicly available. This is causing the build pipeline to break at the installing helm chart step.
=> Upgrade helm orb to 1.1.2

docs/git-crypt.md
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-496)
Update the docs to correctly refer to the `--trusted` flag.
=> Reorder the --trusted flag

Dockerfile
Fix to allow docker to build 
Adding RUN yarn to Dockerfile to ensure webpacker is up to date for Docker build
=> add run yarn to dockerfile

lib/tasks/demodata.rake, spec/tasks/demodata_spec.rb
Amend demo data to add sequential hearing days
This is needed to emulate more realistic
date ordering of hearings and their hearing_days
for the purposes of demoing pagination in VCD.
currently the demo data generated byt this task
creates hearings all with the same exact hearing
days (and time) - this is unrealistic.
VCD related [CBO-1417](https://dsdmoj.atlassian.net/browse/CBO-1417)
=> Amend demo data to add sequential hearing days

.circleci/config.yml
We're currently getting this error on CircleCI at the `install_on_cluster` step:
```
helm upgrade --install hmcts-common-platform-mock-api ./helm_deploy/hmcts-common-platform-mock-api "$@"
Error: UPGRADE FAILED: timed out waiting for the condition
```
This PR doubles the timeout from the default 300s (5 mins).
If this doesn't fix the issue, we will have to investigate further.
=> Increase timeout for helm upgrade

db/migrate/20210128160503_add_judicial_result_offence_relationship.rb, db/schema.rb
We cannot delete JudicialResults before deleting their dependent
JuidicalResultPrompts.
We use ActiveRecord's .delete_all in order to benefit from the
`dependent: :destroy` that we specified on the `JudicialResult`
model.
This is causing the deployment to fail on master.
[Link to story](https://dsdmoj.atlassian.net/browse/-LASBXXX)
=> Fix JudicialResult migration

.circleci/config.yml, db/migrate/20210128160503_add_judicial_result_hearing_relationship.rb, db/migrate/20210128160503_add_judicial_result_offence_relationship.rb
* Use `destroy_all` instead of `delete_all` to trigger dependent destroy callback
* Remove wait flag for `helm-upgrade`
=> Use destroy_all instead of delete_all to trigger dependent destroy callback

app/controllers/admin/judicial_results_controller.rb, app/models/judicial_result.rb, app/models/next_hearing.rb, app/views/admin/hearings/_add_judicial_result.html.erb, app/views/admin/hearings/_form.html.erb, app/views/admin/hearings/show.html.erb, app/views/admin/judicial_results/_form.html.erb, app/views/admin/judicial_results/edit.html.erb, app/views/admin/judicial_results/show.html.erb, config/routes.rb, spec/factories/defendants.rb, spec/factories/offences.rb, spec/requests/admin/judicial_results_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-516)
As an HMCTS mock admin user, I want Date of Next Hearing to be populated.
This was started in https://github.com/ministryofjustice/hmcts-common-platform-mock-api/pull/377, but due to major code conflicts, it was just easier to do it again here.
In the current form of the mock, the Date of Next Hearing is not populated
Date of Next Hearing updated when new offence created using the admin mock tool.
=> CRUD for judicial results + create next hearing

config/routes.rb, spec/requests/admin/judicial_results_spec.rb
The verb used by the app is `PATCH` rather than `PUT`, so the user was unable to update a judicial result.
=> Use HTTP verb PATCH instead of PUT

.circleci/config.yml
Fixes:
```
WARNING: Kubernetes configuration file is group-readable.
This is insecure. Location: /home/circleci/.kube/config
Error: UPGRADE FAILED: timed out waiting for the condition
```
=> Deny read permission to group and others on ~/.kube/config

db/migrate/20210406103836_update_prosecution_case_identifier.rb
This column already exists and allows for null values.
=> Fix migration

app/models/defendant_summary.rb, lib/schemas/global/search/apiDefendantSummary.json
The new HMCTS Common Platform schema removed `defendantFirstName`, `defendantLastName`, and `defendantMiddleName` in favour of just `defendantName`. This breaks VCD, and would break MLRA too, so we're going to push back on this schema change.
This PR reverts back to using `defendantFirstName`, `defendantLastName`, and `defendantMiddleName` on `defendantSummary`.
=> Revert to exposing defendant first, middle and last names

.circleci/config.yml
Update AWS EKS Orb to latest version (1.1.0)
=> Update AWS EKS Orb to latest version (1.1.0)

app/models/prosecution_case.rb
> DEPRECATION WARNING: Directly including `PgSearch` into an Active Record model is deprecated and will be removed in pg_search 3.0.
=> Silence the PgSearch deprecation warning

app/views/admin/court_applications/show.html.erb, app/views/admin/hearing_days/edit.html.erb, app/views/admin/hearing_days/show.html.erb, app/views/admin/hearings/_form.html.erb, app/views/admin/hearings/show.html.erb, app/views/admin/judicial_results/show.html.erb, app/views/admin/prosecution_cases/_defendant.html.erb, app/views/admin/prosecution_cases/_form.html.erb, app/views/admin/prosecution_cases/_hearing.html.erb, app/views/admin/prosecution_cases/show.html.erb, spec/factories/hearing_days.rb, spec/factories/hearings.rb, spec/factories/indicated_pleas.rb
Small style changes in views to make UI and navigation more consistent throughout the app
Alters hearing days factory to have static values in 'non-realistic' factory, and points to realistic hearing day creation when creating a realistic hearing
=> standardise views for consistency

app/controllers/admin/hearings_controller.rb, app/controllers/admin/prosecution_cases_controller.rb, app/controllers/hearings_controller.rb, app/models/hearing.rb, app/models/hearing_summary.rb, app/models/prosecution_case_summary.rb, app/services/hearing_finder.rb, app/views/admin/hearing_days/show.html.erb, app/views/admin/hearings/_form.html.erb, app/views/admin/hearings/show.html.erb, app/views/admin/prosecution_cases/_hearing.html.erb, app/views/admin/prosecution_cases/show.html.erb, db/migrate/20210817165605_update_hearing.rb, db/migrate/20210817165723_set_hearing_model_id_as_id.rb, db/schema.rb, lib/schemas/api/results.api.hearingResultedRequest.json, lib/schemas/global/apiHearing.json, spec/controllers/hearings_controller_spec.rb, spec/factories/hearings.rb, spec/models/hearing_spec.rb, spec/models/hearing_summary_spec.rb, spec/services/hearing_finder_spec.rb
Add hearing_id and sitting_day options to hearing
Allow for a hearing to have multiple hearing ids with different sitting days
Update hearing controller to return hearing with most recent sitting day if sitting day not specified
Run `rails db:migrate` to update hearings table with new changes
Schema validations for hearing have been commented out because we will want them in the future, but are currently unsure of CP schema changes for this functionality. 
[Link to story](https://dsdmoj.atlassian.net/browse/-LASB649)
=> Allow for creation and return of multiday hearing 

app/controllers/admin/prosecution_cases_controller.rb, app/views/admin/prosecution_cases/show.html.erb, spec/views/admin/prosecution_cases/show.html.erb_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-2828)
=> LASB-2828: Added environment selection option.

app/models/hearing_summary.rb
ACD-255 is a bug that only appears in hearing summary payloads containing defence counsels, but the mock API never returns defence counsels in the payload, so this addresses that.
(Note there's already a spec validating the payload which would fail if the below contravened the spec)
[Link to story](https://dsdmoj.atlassian.net/browse/ACD-255)
=> ACD-255: Add defenceCounsel to hearing summary

app/models/court_application_defendant_summary.rb, app/services/laa_representation_order_recorder.rb, config/routes.rb, lib/schemas/api/progression.recordRepresentationOrder.json, spec/requests/representation_orders_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/ACD-586)
Add a new endpoint that can add representation orders to application subject offences
Since the prosecution case endpoint doesn't really care about the prosecution case, I _think_ we can simply reuse the same logic wholesale, and simply be a bit more permissive in the schema.
=> ACD-586: Add rep order endpoint

app/assets/stylesheets/application.css, app/controllers/admin/application_conclusions_controller.rb, app/controllers/admin/application_controller.rb, app/controllers/admin/court_applications_controller.rb, app/controllers/admin/prosecution_cases_controller.rb, app/javascript/packs/application.js, app/models/application_conclusion.rb, app/models/court_application.rb, app/services/application_conclusion_publisher.rb, app/services/court_application_concluder.rb, app/views/admin/court_applications/_form.html.erb, app/views/admin/court_applications/edit.html.erb, app/views/admin/court_applications/show.html.erb, app/views/admin/prosecution_cases/show.html.erb, app/views/layouts/admin/application.html.erb, config/routes.rb, db/migrate/20250328091423_add_result_code_to_court_applications.rb, db/schema.rb, spec/cassettes/court_applications/concluded/success.yml, spec/requests/admin/application_conclusions_spec.rb, spec/services/application_conclusion_publisher_spec.rb, spec/services/court_application_concluder_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/ACD-416)
- Add a button on the court application page allowing us to publish the conclusion of an application to different environments
- Add a result_code attribute to court applications and a UI to set the result code
- Generate a new payload that gets sent to the existing prosecution conclusion CDA endpoint
=> ACD-416: Add mechanism to publish conclusion of an application

app/services/court_application_concluder.rb, spec/services/court_application_concluder_spec.rb
The mock sets the `proceedingsConcluded` value of the appeal payload based on whether all offences are "disposed", so we need to make sure that we set them all as disposed when we conclude the appeal.
=> Make concluding appeals work properly

app/models/defendant_summary.rb, lib/schemas/global/search/apiDefendantSummary.json
The real HMCTS returns masterDefendantId as part of the payload. This PR updates the mock to do the same.
[Link to story](https://dsdmoj.atlassian.net/browse/ACD-757)
=> ACD-757: Add masterDefendantId to the defendant payload

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, README.md
Check for accidentally committed secrets as a hook that runs on commit and on put to GitHub.
=> ACD-765: Pre-commit security scanning

app/controllers/admin/court_applications_controller.rb, app/controllers/admin/prosecution_cases_controller.rb, app/models/court_application.rb, app/models/court_application_summary.rb, app/views/admin/court_applications/show.html.erb, app/views/admin/defendants/show.html.erb, app/views/admin/prosecution_cases/show.html.erb, config/routes.rb, spec/factories/defendants.rb, spec/features/multiple_cases_spec.rb, spec/requests/admin/court_applications_controller_spec.rb
Add UI controls to make it possible to have 2 prosecution cases whose defendants are the same person (i.e. they share a masterDefendantId), and associate both cases with a single court application that is tagged to that masterDefendantId.
[Link to story](https://dsdmoj.atlassian.net/browse/-ACD-698)
=> ACD-698: Allow associating multiple prosecution cases with a court application

config/initializers/assets.rb
I don't know why this only very recently seemed to start biting us, but this line not only unnecessary, it also means that when running locally, for any Rails action that inherits from ActionController::Base rather than ActionController::API, Rails seems to read through the entire contents of the node_modules folder, which can take up to a minute, for no good reason.
=> Remove unnecessary asset config

app/models/defendant_judicial_result.rb, app/models/hearing.rb, app/models/judicial_result.rb
There was always supposed to be a `defendantJudicialResults` section in the hearing payload, but we never used it before, so we've always ignored it. This PR fixes that since we now need that section for breaches
[Link to story](https://dsdmoj.atlassian.net/browse/ACD-949)
=> ACD-949: (Breaches/POCA) Add defendantJudicialResults to hearing payload
